# Generated by Django 3.1.4 on 2020-12-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='todo',
            name='todo_todo_user_id_873df0_idx',
        ),
    ]
